version: "3.3"
services:
  bookstore:
      image: postgres:11
      container_name: bookstore
      environment:
        - POSTGRES_USER=${BOOKSTORE_DB_USER}
        - POSTGRES_PASSWORD=${BOOKSTORE_DB_USER}
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
          - ./postgres-data:/var/lib/postgresql/data
      logging:
        driver: none  

  bookservice:
    build: ../BookService/install/
    container_name: bookservice
    ports:
      - "8090:8090"
    environment:
      - BOOKSTORE_DB_HOST=${BOOKSTORE_DB_HOST}
      - BOOKSTORE_DB_USER=${BOOKSTORE_DB_USER}
      - BOOKSTORE_DB_PW=${BOOKSTORE_DB_PW}
      - BOOKSTORE_PORT=${BOOKSTORE_PORT}
    depends_on:
      - bookstore
    logging:
      driver: none
      
  bookproxy:
    build: ../BookStoreProxy/install/
    container_name: bookproxy
    ports:
      - "8080:8080"
    environment:
      - BOOKSTORE_SERVICE_HOST=${BOOKSTORE_SERVICE_HOST}
      - BOOKSTORE_PORT=${BOOKSTORE_PORT}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - bookservice